name: Build and Test

on: [push]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        platform: [windows]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up GCC
      if: matrix.platform == 'linux' || matrix.platform == 'macos'
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      if: matrix.platform == 'linux' || matrix.platform == 'macos'
      run: |
        if [ "${{ matrix.platform }}" == "linux" ]; then
          sudo apt-get update
          sudo apt-get install -y g++
        fi

    - name: Build and test
      run: |
        make PLATFORM=${{ matrix.platform }} ACTIONS=true
