name: Build on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up MSYS2 environment
      run: |
        choco install msys2
        refreshenv
        pacman -Sy --noconfirm make gcc

    - name: Build
      run: make PLATFORM=windows
